sudo: required
services:
  - docker

before_install:
  - docker build -t metabc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run metabc/react-test npm test -- --coverage

after_success:
  - docker build -t metabc/multi-client ./client
  - docker build -t metabc/multi-nginx ./nginx
  - docker build -t metabc/multi-server ./server
  - docker build -t metabc/multi-worker ./worker
  
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  #Take those images and push to Docker hub
  -docker push metabc/multi-client
  -docker push metabc/multi-nginx
  -docker push metabc/multi-server
  -docker push metabc/multi-worker